### ISSUE TITLE
Crash when underground, specifically. Something related to sound effects. 

### ISSUE THREAD

**Issue by AzathothFLZ** [OreCruncher/Environs#4] opened 2020-02-21 06:21 UTC
The mod was working fine when i added to my Modpack, then i went underground and it keeps crashing. I tried removing AmbientSounds 3 to solve it, but no luck.

Here's the log: https://pastebin.com/K50Np5zH
---- Minecraft Crash Report ----
// There are four lights!
 
Time: 21/02/20 03:16
Description: Unexpected error
 
java.lang.NullPointerException: Unexpected error
    at org.orecruncher.environs.scanner.RandomBlockEffectScanner.interestingBlock(RandomBlockEffectScanner.java:61) ~[?:1.14.4-0.0.5.0] {re:classloading,pl:runtimedistcleaner:A}
    at org.orecruncher.environs.scanner.Scanner.tick(Scanner.java:144) ~[?:1.14.4-0.0.5.0] {re:classloading,pl:runtimedistcleaner:A}
    at org.orecruncher.environs.handlers.AreaBlockEffects.process(AreaBlockEffects.java:51) ~[?:1.14.4-0.0.5.0] {re:classloading,pl:eventbus:A,pl:runtimedistcleaner:A}
    at org.orecruncher.environs.handlers.Manager.onTick(Manager.java:118) ~[?:1.14.4-0.0.5.0] {re:classloading}
    at org.orecruncher.environs.handlers.Manager.clientTick(Manager.java:131) ~[?:1.14.4-0.0.5.0] {re:classloading}
    at net.minecraftforge.eventbus.ASMEventHandler_859_Manager_clientTick_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
    at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
    at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
    at net.minecraftforge.fml.hooks.BasicEventHooks.onPreClientTick(BasicEventHooks.java:104) ~[?:?] {re:classloading}
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1274) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
    at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:869) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
    at net.minecraft.client.main.Main.main(SourceFile:155) ~[ForgeOptiFine%201.14.4.jar:?] {re:classloading}
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212] {}
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_212] {}
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_212] {}
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_212] {}
    at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.14.4-28.2.0.jar:28.2] {}
    at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
    at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
    at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
    at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
    at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

**Comment by OreCruncher** [comment] 2020-02-21 06:55
I believe this to be a dupe of #1 .  It looks like there is a blockstate that was registered after Environs scanned the registry.

**Comment by AzathothFLZ** [comment] 2020-02-21 14:13
Allright. I just read the thread and i'll try to install the test version you made to see if it solves. If not, i'll try every individual mod with Environs to find any incompatibilities. Thanks for the reply anyway.

**Comment by AzathothFLZ** [comment] 2020-02-21 14:32
Yup. I've been playing for 15 minutes and no crashes (i was getting crashes every 1 minute). You, sir, are a genious. 
I'll leave the thread open in case it crashes again till tomorrow, but anyway, thanks for the fix.

**Comment by OreCruncher** [comment] 2020-02-22 17:53
Pushed release build 0.1.0.0 to CurseForge

**Closed as completed by OreCruncher** 2020-02-22 17:53 UTC
